# Generated by Django 4.0.2 on 2022-02-13 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import milk.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='year2022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jan', models.JSONField(default=milk.models.year2022.call_Jan)),
                ('Feb', models.JSONField(default=milk.models.year2022.call_Feb)),
                ('Mar', models.JSONField(default=milk.models.year2022.call_Mar)),
                ('Apr', models.JSONField(default=milk.models.year2022.call_Apr)),
                ('May', models.JSONField(default=milk.models.year2022.call_May)),
                ('Jun', models.JSONField(default=milk.models.year2022.call_Jun)),
                ('Jul', models.JSONField(default=milk.models.year2022.call_Jul)),
                ('Aug', models.JSONField(default=milk.models.year2022.call_Aug)),
                ('Sep', models.JSONField(default=milk.models.year2022.call_Sep)),
                ('Oct', models.JSONField(default=milk.models.year2022.call_Oct)),
                ('Nov', models.JSONField(default=milk.models.year2022.call_Nov)),
                ('Dec', models.JSONField(default=milk.models.year2022.call_Dec)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
