# Generated by Django 4.0.2 on 2022-10-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
